version: '3.8'
services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    tty: true
    working_dir: /usr/src/app
    environment:
      SSHHOST: ${IP_ADDRESS}
      SSHPORT: 22
      SSHUSER: ${USER}
      SSHAUTH: publickey
      SSHKEY: ~/.ssh/nossh
      BASE: /controller/p/w
    volumes:
      - ~/.ssh:/root/.ssh

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/wetty.template
      - ./auth:/usr/src/
    ports:
      - '8090:80'
    environment:
      - NGINX_DOMAIN=default_server      
      - NGINX_PORT=80
      - WETTY_HOST=wetty
      - WETTY_PORT=3000
      - TARGET_PROTOCOL=http
      - TARGET_URL=${IP_ADDRESS}
      - TARGET_PORT=8080
    command: >-
      /bin/bash -c "envsubst
      '$${NGINX_DOMAIN},$${NGINX_PORT},$${WETTY_HOST},$${WETTY_PORT},$${TARGET_PROTOCOL},$${TARGET_URL},$${TARGET_PORT}' <
      /etc/nginx/conf.d/wetty.template > /etc/nginx/conf.d/default.conf && cat /usr/src/nginx.htpasswd > /etc/nginx/conf.d/nginx.htpasswd && nginx -g 'daemon off;'"
          
networks:
  default:
    name: nossh-proxy-base
